<?php

use Magezil\BuyList\Api\Data\BuyListInterface;

/**
 * @var \Magezil\BuyList\Block\Listing $block
 */
?>
<?php if ($block->hasBuyLists()) : ?>
    <div class="table-wrapper">
        <table class="data table">
            <thead>
                <tr>
                    <th scope="col" class="col"><?= __('Buy List #') ?></th>
                    <th scope="col" class="col"><?= __('Title') ?></th>
                    <th scope="col" class="col"><?= __('Is active') ?></th>
                    <th scope="col" class="col"><?= __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php /** @var BuyListInterface $buyList */ ?>
                <?php foreach ($block->getBuyLists() as $buyList) : ?>
                    <tr>
                        <td class="col"><?= $buyList->getId() ?></td>
                        <td class="col"><?= $buyList->getTitle() ?></td>
                        <td class="col"><?= $block->formatActive($buyList->getIsActive()) ?></td>
                        <td class="col">
                            <a class="action view" href="<?= $block->getUrlToView($buyList->getId()) ?>">
                                <span><?= __('View Buy List') ?></span>
                            </a>
                            <?php if ($buyList->getIsActive()) : ?>
                                <a class="action order" href="<?= $block->getUrlToReorder($buyList->getId()) ?>">
                                    <span><?= __('Reorder') ?></span>
                                </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty">
        <span><?= __('You have not buy lists yet.') ?></span>
    </div>
<?php endif ?>
