<?php

/**
 * @var \Magezil\BuyList\Block\Listing $block
 */
?>
<?php if ($block->hasBuyLists()) : ?>
    <?php $myBuyListsJsonData = $block->getMyBuyListsJsonData(); ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "buy-list-table": {
                            "component": "Magezil_BuyList/js/myLists/table",
                            "items": <?= $myBuyListsJsonData; ?>
                        }
                    }
                }
            }
        }
    </script>

    <div data-bind="scope: 'buy-list-table'" id="buyListTable">
        <!-- ko template: getTemplate() -->
        <!-- /ko -->
    </div>

    <?php if ($block->getPagerHtml()) : ?>
        <div class="toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty">
        <span><?= __('You have not buy lists.') ?></span>
    </div>
<?php endif ?>
